name: plugintest
description: A Flutter plugin project.
version: 0.0.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.plugintest
        pluginClass: PlugintestPlugin
      ios:
        pluginClass: PlugintestPlugin
